name: lint and build

on: 
  push:
    branches:
      - dev

jobs:
  build-push-ghcr:
    name: build and push ghcr.io
    runs-on: ${{ matrix.os }}

    permissions:
      packages: write
      contents: read

    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: write .env
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: echo $ENV_FILE >> .env

      - name: image build
        run: docker build -t frontend-dev .

      - name: login to registry
        run: echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: push image to registry
        env:
          LATEST_VERSION: ${{ github.event.release.tag_name }}
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/frontend-dev:latest
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          docker tag frontend-dev $IMAGE_ID
          docker push $IMAGE_ID

  deploy-aws:
    name: deploy to ec2
    runs-on: ${{ matrix.os }}

    needs:
      - build-push-ghcr

    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: configure ssh
        env:
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_PEM }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/hms.pem
          chmod 700 ~/.ssh/hms.pem
          cat >> ~/.ssh/config << END
          Host development 
            Hostname $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/hms.pem
            StrictHostKeyChecking=no
          END

      - name: connect ec2, pull and run container
        run: ssh development '
          sudo docker rm -f $(docker ps -aqf "name=clinic-frontend-dev") || true &&
          sudo docker pull ghcr.io/altera-capston-41/frontend-dev:latest &&
          sudo docker run -dp 19028:3000 --name clinic-frontend-dev ghcr.io/altera-capston-41/frontend-dev:latest'

      - name: restart container
        run: ssh development '
          sudo docker restart clinic-frontend-dev'
